var config = {};

//Define update interval with cron sintax
config.cron = '*/30 * * * * *';

// Your 123solar API link
config.SOLAR_HOST_URL="http://192.168.0.250/123solar/programs/programlive.php";

// Your Domoticz ip and port, remember to NOT put trailing slash like http://domoticz-ip<:port>
// If your Domoticz need Authentication http://<username:password@>domoticz-ip<:port>
config.DOMOTICZ_HOST_URL="http://127.0.0.1:8081";

// IDX Numbers JSON, replicate all the "1" part changing the 1 in the inverter's number, if you have more than 1 inverter
config.IDX = {
	"1" : {
		"I1P" : 55, //			Usage		Electric	100.5 Watt
		"I2P" : 56, //			Usage		Electric	100.5 Watt
		"I1V" : 46, //			General		Voltage		170.000 V
		"I2V" : 47, //			General		Voltage		170.000 V
		"I1A" : 48, //			General		Current		0.600 A
		"I2A" : 49, //			General		Current		0.600 A
		"GV" : 51, //			General		Voltage		235.000 V
		"GA" : 50, //			General		Current		0.600 A		
		"FRQ" : 0, //			Power Frequency, I don't know which type!
		"EFF" : 53, //			General		Percentage	81.50%
		"INVT" : 52, //			Temp		TFA 30.3133	60.0°C
		"Total_Power" : 54 //	General		kWh			8549.873 kWh
	}
};

//Power generated by all Inverters
config.solar_Power_IDX = 0; //          General     kWh         12769.776 kWh

//Power Meter IDX, if you have one, so Domoticz can calculate power usage. 0 both if you don't have
config.pow_Meter_IDX = 0;
config.power_Consumption_IDX = 0; //   RFXMeter    counter     16257.239 kWh

//Developing variables
config.DEBUG = false; //Write to console.log all the datas
config.TEST = false; //Dry-run, it just read from 123Solar, does NOT update any value on Domoticz

module.exports = config;